FROM alpine:3.20 AS build
RUN apk add --no-cache build-base curl-dev curl-static sqlite-dev sqlite-static openssl-dev openssl-libs-static git lua5.4 lua5.4-dev

WORKDIR /app
COPY . .

RUN cd concord && make -j$(nproc) \
    && cp gencodecs/*.h include/ \
    && cp core/*.h include/
RUN make release-static
